#!/bin/sh
# Auto format staged files before commit
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|js|json)$')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs bunx biome check --write --no-errors-on-unmatched
echo "$FILES" | xargs git add

exit 0
